import { TILE_SIZE } from 'libs/worldConstants'

export const enemies = [
  { type: 'goomba', x: 8, y: 1 },
  { type: 'koopa', x: 20, y: 1 },
  { type: 'buzzy', x: 16, y: 1 },
]

export const elements = [
  { type: 'Solid', x: 135, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 136, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 136, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 137, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 137, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 137, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 138, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 138, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 138, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 138, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },

  { type: 'Solid', x: 141, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 141, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 141, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 141, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 142, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 142, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 142, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 143, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 143, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 144, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },

  { type: 'Solid', x: 149, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 150, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 150, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 151, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 151, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 151, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 152, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 152, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 152, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 152, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 153, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 153, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 153, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 153, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },

  { type: 'Solid', x: 156, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 156, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 156, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 156, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 157, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 157, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 157, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 158, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 158, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 159, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },

  { type: 'Solid', x: 184, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 185, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 185, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 186, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 186, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 186, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 187, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 187, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 187, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 187, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 188, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 188, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 188, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 188, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 188, y: 5, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 189, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 189, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 189, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 189, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 189, y: 5, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 189, y: 6, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 190, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 190, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 190, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 190, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 190, y: 5, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 190, y: 6, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 190, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 191, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 191, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 191, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 191, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 191, y: 5, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 191, y: 6, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 191, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 191, y: 8, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 192, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 192, y: 2, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 192, y: 3, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 192, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 192, y: 5, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 192, y: 6, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 192, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Solid', x: 192, y: 8, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  
  { type: 'Solid', x: 201, y: 1, size: 1, width: TILE_SIZE, height: TILE_SIZE },

  { type: 'Mystery', x: 17,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Mystery', x: 22,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE, content: 'mushroom' },
  { type: 'Mystery', x: 23,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE, content: 'flower' },
  { type: 'Mystery', x: 24,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE, content: 'star' },
  { type: 'Mystery', x: 81,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Mystery', x: 95,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Mystery', x: 107, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Mystery', x: 110, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Mystery', x: 110, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Mystery', x: 113, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Mystery', x: 130, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Mystery', x: 131, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Mystery', x: 173, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },

  { type: 'Mystery', x: 65,  y: 5, size: 1, width: TILE_SIZE, height: TILE_SIZE, hidden: 1 },
  
  { type: 'Brick', x: 21,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 23,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 25,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 78,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 79,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 80,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 82,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 83,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 84,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 85,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 86,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 87,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 88,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 92,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 93,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 94,  y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 95,  y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 100, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 101, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 119, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 122, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 123, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 124, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 129, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 130, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 131, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 132, y: 7, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 171, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 172, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },
  { type: 'Brick', x: 174, y: 4, size: 1, width: TILE_SIZE, height: TILE_SIZE },

  { type: 'Pipe', x: 29,  y: 1, size: 1, width: TILE_SIZE * 2, height: 128 },
  { type: 'Pipe', x: 39,  y: 1, size: 2, width: TILE_SIZE * 2, height: 192 },
  { type: 'Pipe', x: 47,  y: 1, size: 3, width: TILE_SIZE * 2, height: 256 },
  { type: 'Pipe', x: 58,  y: 1, size: 3, width: TILE_SIZE * 2, height: 256 },
  { type: 'Pipe', x: 166, y: 1, size: 1, width: TILE_SIZE * 2, height: 128 },
  { type: 'Pipe', x: 182, y: 1, size: 1, width: TILE_SIZE * 2, height: 128 },
  
  { type: 'Floor', x: 0,   y: 0, size: 69, width: 69 * TILE_SIZE, height: TILE_SIZE },
  { type: 'Floor', x: 71,  y: 0, size: 16, width: 16 * TILE_SIZE, height: TILE_SIZE },
  { type: 'Floor', x: 90,  y: 0, size: 64, width: 64 * TILE_SIZE, height: TILE_SIZE },
  { type: 'Floor', x: 156, y: 0, size: 62, width: 62 * TILE_SIZE, height: TILE_SIZE },
]
